const usuarios = [
  {
    id: "1",
    nombre: "Laura Martínez",
    edad: 28,
    ciudad: "Bogotá",
    especialidad: "Dermatología",
    email: "laura.martinez@example.com",
  },
  {
    id: "2",
    nombre: "Carlos Rojas",
    edad: 34,
    ciudad: "Medellín",
    especialidad: "Cardiología",
    email: "carlos.rojas@example.com",
  },
  {
    id: "3",
    nombre: "Valentina López",
    edad: 26,
    ciudad: "Cali",
    especialidad: "Pediatría",
    email: "valentina.lopez@example.com",
  },
  {
    id: "4",
    nombre: "Juan Pérez",
    edad: 41,
    ciudad: "Barranquilla",
    especialidad: "Neurología",
    email: "juan.perez@example.com",
  },
  {
    id: "5",
    nombre: "Diana Gómez",
    edad: 30,
    ciudad: "Cartagena",
    especialidad: "Ginecología",
    email: "diana.gomez@example.com",
  },
  {
    id: "6",
    nombre: "Andrés Torres",
    edad: 38,
    ciudad: "Manizales",
    especialidad: "Traumatología",
    email: "andres.torres@example.com",
  },
  {
    id: "7",
    nombre: "Natalia Ramírez",
    edad: 27,
    ciudad: "Pereira",
    especialidad: "Psiquiatría",
    email: "natalia.ramirez@example.com",
  },
  {
    id: "8",
    nombre: "Felipe Castillo",
    edad: 32,
    ciudad: "Bucaramanga",
    especialidad: "Odontología",
    email: "felipe.castillo@example.com",
  },
  {
    id: "9",
    nombre: "Camila Herrera",
    edad: 29,
    ciudad: "Cúcuta",
    especialidad: "Oftalmología",
    email: "camila.herrera@example.com",
  },
  {
    id: "10",
    nombre: "Julián Rivera",
    edad: 36,
    ciudad: "Neiva",
    especialidad: "Oncología",
    email: "julian.rivera@example.com",
  },
];

export default usuarios;
